---
title: "HGDP_TGP_pca_admixture"
author: "Christian Porras"
date: "7/12/2020"
output: html_document
---

```{r}
library(tidyverse)
```


# TGP PCA
```{r}
TGP_eigvec <- read_table2("../data/TGP.eigenvec",col_names = FALSE)
TGP_eigval <- scan("../data/TGP.eigenval")
```

## Clean eigvecs and label individuals
```{r}
# remove repeat ID column
TGP_eigvec <- TGP_eigvec[,-1]
# name columns
names(TGP_eigvec)[1] <- "ind"
names(TGP_eigvec)[2:ncol(TGP_eigvec)] <- paste0("PC", 1:(ncol(TGP_eigvec)-1))

#### TODO:
# use TGP .ind to relabel individuals with pop/super pop
```

### Label indivis with pop
```{r}
# From previous work...
pops <- read.csv(file="../data/1K_genomes_PCA_noanon.csv")[c(1,5,6)]
# sort by ID
pops <- pops[order(pops$Sample_ID),]
# Add population label columns to TGP
TGP_eigvec <- add_column(TGP_eigvec, super_pop = pops$Super_Population, .after = "ind")
TGP_eigvec <- add_column(TGP_eigvec, pop = pops$Population, .before = "PC1")
```

### Make df of eigval loadings
```{r}
perc_var_expl <- data.frame(PC = 1:20, pve = TGP_eigval/sum(TGP_eigval)*100) 
```

## Plot eigval loadings
```{r}
loadings <- ggplot(perc_var_expl, aes(PC,pve)) +
  geom_bar(stat = "identity")
loadings + ylab("Percentage variance explained") + theme_light()
```

## Plot PCs
```{r}
pcs <- ggplot(TGP_eigvec, aes(PC1, PC2, shape = super_pop, col = pop)) +
  geom_point(size=3) +
  xlab(paste0("PC1 (", signif(perc_var_expl$pve[1],3), "%)")) + 
  ylab(paste0("PC2 (", signif(perc_var_expl$pve[2],3), "%)")) + 
  theme_light()
pcs
```

# HGDP PCA
```{r}
HGDP_eigvec <- read_table2("../data/HGDP_plus.eigenvec",col_names = FALSE)
HGDP_eigval <- scan("../data/HGDP_plus.eigenval")
```

## Clean eigvecs and label individuals
```{r}
# remove repeat ID column
HGDP_eigvec <- HGDP_eigvec[,-1]
# name columns
names(HGDP_eigvec)[1] <- "ind"
names(HGDP_eigvec)[2:ncol(HGDP_eigvec)] <- paste0("PC", 1:(ncol(HGDP_eigvec)-1))
### TODO
# Label w /ind files from .ped
```


## Plot eigval loadings
```{r}
perc_var_expl <- data.frame(PC = 1:20, pve = HGDP_eigval/sum(HGDP_eigval)*100) 
loadings <- ggplot(perc_var_expl, aes(PC,pve)) +
  geom_bar(stat = "identity")
loadings + ylab("Percentage variance explained") + theme_light()
```

## Plot PCs
```{r}
pcs <- ggplot(HGDP_eigvec, aes(PC1, PC2)) +
  geom_point(size=3) +
  xlab(paste0("PC1 (", signif(perc_var_expl$pve[1],3), "%)")) + 
  ylab(paste0("PC2 (", signif(perc_var_expl$pve[2],3), "%)")) + 
  theme_light()
pcs
```

# Merge TGP and HGDP
```{r}
# Make list of common snps
TGP_map <- read.delim("../data/TGP_text.map", header = FALSE, quote = "")
HGDP_map <- read.delim("../data/HGDP_plus_text.map", header = F, quote = "")
common_snps <- which(TGP_map$V2 %in% HGDP_map$V2)
write.table(TGP_map$V2[common_snps], file="list.snps", sep="\t", 
            col.names = F, row.names = F, quote = F)
```

### extract common snps in both data
```{bash}
./../plink_mac_20200616/plink --bfile ../data/HGDP_plus --extract list.snps --make-bed --out HGDP_common
```

```{bash}
./../plink_mac_20200616/plink --bfile ../data/TGP --extract list.snps --make-bed --out TGP_common
```
### merge in plink
```{bash}
./../plink_mac_20200616/plink --bfile HGDP_common --bmerge TGP_common.bed TGP_common.bim TGP_common.fam --make-bed --out merge_TGP_HGDP
```
### debug plink flips
```{bash}
./../plink_mac_20200616/plink --bfile ../data/TGP --flip-scan
```


# ADMIXTURE props

## get num_clusters k
```{r}
## just using number of TGP pops for now...
k <- length(unique(pops$Population))
print(k)
```

## call ADMIXTURE
```{bash}
./../admixture_macosx-1.3.0/admixture 
```

